package plan

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/seaweedfs/seaweed-up/pkg/cluster/spec"
)

// MarshalOptions controls header-comment emission on the rendered
// cluster.yaml. Zero-value is fine; only the Now field is commonly
// overridden (by tests, for a stable golden file).
type MarshalOptions struct {
	// InventoryPath is the path of the inventory file that produced this
	// spec, embedded into the header comment for traceability.
	InventoryPath string

	// Now lets tests stamp a fixed timestamp; defaults to time.Now().UTC().
	Now time.Time
}

// Marshal renders spec as a cluster.yaml-compatible byte slice. A short
// header comment is prepended so the generated file is obviously
// machine-produced and safe to hand-edit. Delegates to yaml.v3, which is
// already used everywhere else in the codebase.
func Marshal(spec *spec.Specification, opts MarshalOptions) ([]byte, error) {
	if spec == nil {
		return nil, fmt.Errorf("spec is nil")
	}
	body, err := yaml.Marshal(spec)
	if err != nil {
		return nil, fmt.Errorf("marshal spec: %w", err)
	}

	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}

	var header bytes.Buffer
	header.WriteString("# Generated by seaweed-up plan")
	if opts.InventoryPath != "" {
		fmt.Fprintf(&header, " from %s", opts.InventoryPath)
	}
	fmt.Fprintf(&header, " on %s.\n", now.Format(time.RFC3339))
	header.WriteString("# Safe to hand-edit. Re-running plan against this file currently\n")
	header.WriteString("# refuses to overwrite unless --force is passed; Phase 3 will add\n")
	header.WriteString("# append-merge that preserves comments and hand edits.\n")

	// If any filer emitted an empty Config (no --filer-backend supplied),
	// call it out at the top so operators know where to fill in.
	if specHasBlankFilerConfig(spec) {
		header.WriteString("#\n")
		header.WriteString("# NOTE: filer_servers[*].config is empty. Fill in the metadata-store\n")
		header.WriteString("# credentials before deploy, or re-run plan with --filer-backend.\n")
	}
	// Similarly call out CHANGE_ME admin credentials. The AdminServerSpec
	// only writes auth flags when set, so leaving CHANGE_ME in place
	// would start an admin UI with a weak password and leaving it empty
	// would leave the UI unauthenticated entirely.
	if specHasPlaceholderAdminCredentials(spec) {
		header.WriteString("#\n")
		header.WriteString("# NOTE: admin_servers[*].admin_password is the placeholder \"CHANGE_ME\".\n")
		header.WriteString("# Replace it with a real secret (loaded from a secret manager if possible)\n")
		header.WriteString("# before deploy — an unfilled value is NOT ignored by the admin UI.\n")
	}
	header.WriteString("\n")

	// yaml.Marshal always ends in a newline; concatenate directly.
	out := append(header.Bytes(), body...)
	return out, nil
}

// specHasBlankFilerConfig reports whether any filer_server entry was
// emitted without a Config map, signalling an unwired metadata store.
func specHasBlankFilerConfig(s *spec.Specification) bool {
	for _, f := range s.FilerServers {
		if len(f.Config) == 0 {
			return true
		}
	}
	return false
}

// specHasPlaceholderAdminCredentials reports whether any admin_server
// entry still carries the CHANGE_ME placeholder password.
func specHasPlaceholderAdminCredentials(s *spec.Specification) bool {
	for _, a := range s.AdminServers {
		if a.AdminPassword == AdminPasswordPlaceholder {
			return true
		}
	}
	return false
}

// UnmarshalForRoundTrip is a convenience used by tests to parse the
// rendered output back through spec.Specification and confirm that
// deploy would still accept it. Returns a descriptive error when
// round-trip fails.
func UnmarshalForRoundTrip(data []byte) (*spec.Specification, error) {
	// Strip the header comment block so yaml.Unmarshal sees only the
	// document body. yaml.v3 is happy with comments, but we round-trip
	// via strings.TrimSpace to be defensive.
	trimmed := strings.TrimSpace(string(data))
	out := &spec.Specification{}
	if err := yaml.Unmarshal([]byte(trimmed), out); err != nil {
		return nil, fmt.Errorf("round-trip unmarshal: %w", err)
	}
	return out, nil
}
