# golangci-lint configuration for v2
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
  exclusions:
    rules:
      # Ignore errors in defer statements (common pattern)
      - linters:
          - errcheck
        source: "defer"
      # Ignore test files for some linters
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
