# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Check for errors on type assertions
    check-type-assertions: false
    # Check for errors on blank identifier assignments
    check-blank: false

issues:
  # Don't skip any issues
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude some common patterns
  exclude-rules:
    # Ignore errors in defer statements (common pattern)
    - linters:
        - errcheck
      source: "defer"
    
    # Ignore test files for some linters
    - path: _test\.go
      linters:
        - errcheck

output:
  formats:
    colored-line-number: {}

