apiVersion: v1
kind: Namespace
metadata:
    labels:
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: seaweedfs
    name: production
---
apiVersion: v1
data:
    cluster-name: ""
    replication: "000"
kind: ConfigMap
metadata:
    name: seaweedfs-config
    namespace: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: seaweedfs
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: seaweedfs
        component: master
    name: seaweedfs-master-0
    namespace: production
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seaweedfs
            component: master
            instance: master-0
    template:
        metadata:
            labels:
                app: seaweedfs
                component: master
                instance: master-0
        spec:
            containers:
                - command:
                    - /usr/bin/weed
                    - master
                    - -port=0
                    - -peers=
                  env:
                    - name: POD_NAMESPACE
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
                  image: chrislusf/seaweedfs:latest
                  livenessProbe:
                    httpGet:
                        path: /cluster/status
                        port: 0
                    initialDelaySeconds: 30
                    timeoutSeconds: 10
                  name: seaweedfs
                  ports:
                    - containerPort: 0
                      name: http
                      protocol: TCP
                  readinessProbe:
                    httpGet:
                        path: /cluster/status
                        port: 0
                    initialDelaySeconds: 5
                    timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: seaweedfs
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: seaweedfs
        component: master
    name: seaweedfs-master-0
    namespace: production
spec:
    ports:
        - name: http
          port: 0
          protocol: TCP
          targetPort: 0
    selector:
        app: seaweedfs
        component: master
        instance: master-0
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: seaweedfs
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: seaweedfs
        component: volume
    name: seaweedfs-volume-0
    namespace: production
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seaweedfs
            component: volume
            instance: volume-0
    serviceName: seaweedfs-volume-0
    template:
        metadata:
            labels:
                app: seaweedfs
                component: volume
                instance: volume-0
        spec:
            containers:
                - command:
                    - /usr/bin/weed
                    - volume
                    - -port=0
                    - -mserver=localhost:9333
                    - -dir=/data
                  image: chrislusf/seaweedfs:latest
                  name: seaweedfs
                  ports:
                    - containerPort: 0
                      name: http
                      protocol: TCP
                  volumeMounts:
                    - mountPath: /data
                      name: data
    volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
            storageClassName: fast-ssd
---
apiVersion: v1
kind: Service
metadata:
    name: seaweedfs-volume-0
    namespace: production
spec:
    ports:
        - name: http
          port: 0
          targetPort: 0
    selector:
        app: seaweedfs
        component: volume
        instance: volume-0
    type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: seaweedfs
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: seaweedfs
        component: volume
    name: seaweedfs-volume-1
    namespace: production
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seaweedfs
            component: volume
            instance: volume-1
    serviceName: seaweedfs-volume-1
    template:
        metadata:
            labels:
                app: seaweedfs
                component: volume
                instance: volume-1
        spec:
            containers:
                - command:
                    - /usr/bin/weed
                    - volume
                    - -port=0
                    - -mserver=localhost:9333
                    - -dir=/data
                  image: chrislusf/seaweedfs:latest
                  name: seaweedfs
                  ports:
                    - containerPort: 0
                      name: http
                      protocol: TCP
                  volumeMounts:
                    - mountPath: /data
                      name: data
    volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
            storageClassName: fast-ssd
---
apiVersion: v1
kind: Service
metadata:
    name: seaweedfs-volume-1
    namespace: production
spec:
    ports:
        - name: http
          port: 0
          targetPort: 0
    selector:
        app: seaweedfs
        component: volume
        instance: volume-1
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: seaweedfs-filer-0
    namespace: production
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seaweedfs
            component: filer
            instance: filer-0
    template:
        metadata:
            labels:
                app: seaweedfs
                component: filer
                instance: filer-0
        spec:
            containers:
                - command:
                    - /usr/bin/weed
                    - filer
                    - -port=0
                    - -master=localhost:9333
                  image: chrislusf/seaweedfs:latest
                  name: seaweedfs
                  ports:
                    - containerPort: 0
                      name: http
---
apiVersion: v1
kind: Service
metadata:
    name: seaweedfs-filer-0
    namespace: production
spec:
    ports:
        - name: http
          port: 0
          targetPort: 0
    selector:
        app: seaweedfs
        component: filer
        instance: filer-0
    type: NodePort
